/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculatorHeading = new javax.swing.JLabel();
        Number1 = new javax.swing.JLabel();
        Number2 = new javax.swing.JLabel();
        num1TF = new javax.swing.JTextField();
        num2TF = new javax.swing.JTextField();
        OperationCombo = new javax.swing.JComboBox<>();
        PerformOperationBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        ResultLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CalculatorHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CalculatorHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CalculatorHeading.setText("Calculator");

        Number1.setText("Number 1");

        Number2.setText("Number 2");

        OperationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the operation from here", "Addition", "Substraction", "Multiplication", "Division", "Modulo Division" }));

        PerformOperationBtn.setText("Perform Operation");
        PerformOperationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformOperationBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        ResultLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResultLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultLbl.setText("Results Are Shown Here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalculatorHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number1)
                                        .addGap(18, 18, 18)
                                        .addComponent(num1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PerformOperationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(OperationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(num2TF, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                                .addGap(0, 32, Short.MAX_VALUE))
                            .addComponent(ResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CalculatorHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number1)
                    .addComponent(num1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number2)
                    .addComponent(num2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(OperationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PerformOperationBtn)
                .addGap(18, 18, 18)
                .addComponent(ResetBtn)
                .addGap(18, 18, 18)
                .addComponent(ResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        num1TF.setText("");
        num2TF.setText("");
        ResultLbl.setText("Results Are Shown Here");
        OperationCombo.setSelectedIndex(0);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void PerformOperationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformOperationBtnActionPerformed
        // TODO add your handling code here:
        double num1 = Double.parseDouble(num1TF.getText());
        double num2 = Double.parseDouble(num2TF.getText());
        String operation = (String) OperationCombo.getSelectedItem();
        double result;
        switch(operation){
            case "Addition" -> {
                result= num1+num2;
                ResultLbl.setText("Addition of Both is: "+result);
            }
            case "Substraction" -> {
                result = num1-num2;
                ResultLbl.setText("Substraction of Both is: "+result);
            }
            case "Multiplication" ->{
                result = num1*num2;
                ResultLbl.setText("Multiplication of Both is: "+result);
            }
            case "Division" ->{
                result = num1/num2;
                ResultLbl.setText("Multiplication of Both is: "+result);
            }
            case "Modulo Division" ->{
                result = num1%num2;
                ResultLbl.setText("Multiplication of Both is: "+result);
            }
            default ->{
                ResultLbl.setText("Select An Operation");
            }
        }
    }//GEN-LAST:event_PerformOperationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CalculatorHeading;
    private javax.swing.JLabel Number1;
    private javax.swing.JLabel Number2;
    private javax.swing.JComboBox<String> OperationCombo;
    private javax.swing.JButton PerformOperationBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel ResultLbl;
    private javax.swing.JTextField num1TF;
    private javax.swing.JTextField num2TF;
    // End of variables declaration//GEN-END:variables
}
